### ISSUE TITLE
Criação de objetos resolvidos, e alteração?

### ISSUE THREAD

**Issue by mkacunha** [soujava/bulletproof#1]
Olá @otaviojava , vi sua palestra no TDC sobre Designing Bulletproof Code, e tenho uma dúvida: eu já implementei muitas vezes essa arquitetura, e enquanto estava criado meus objetos tudo lindo, mas quando eu precisava alterar, me via quebrar o encapsulamento ou as vezes sair duplicando validações dos vuilders em setters. Já cheguei até fazer algumas implementações onde a entidade se transformava em um builder para depois se tranformar em entidade novamente, e assim reaproveitar as validações. Como o esquema das interfaces fluente fazendo com que a própria entidade implemente as interfaces, resolve talvez o problema da alteração desde que você não tenha nenhum campo onde só pode ser populado durante a criação. Como você sugere a implementação de alteração de objetos utilizando essa arquitetura de builder e interfaces fluentes?

**Comment by otaviojava** [comment]
olá @mkacunha uma sugestão, seria fazer com que o builder tenha como parâmetro a entidade em si.

```java
Pessoa pessoa = ...;
Pessoa.builder(pessoa).withName("Name Updated');
```

Também nada impede que você tenha um setter com validação.

```java
Pessoa pessoa = ...;
pessoa.setName("Name updated");// a sua validação no setter
```

Se a regra for simples, é chato, mas não vejo muito problema para duplicar. Cria testes unitários para garantir tal comportamento.
Se existe uma super regra de validação o When make a type é sempre uma boa solução, assim, o setter só validaria se o valor é nulo, caso o campo seja obrigatório.
https://martinfowler.com/ieeeSoftware/whenType.pdf

**Comment by mkacunha** [comment]
Legal @otaviojava, é o que costumo fazer mesmo. Muito obrigado pela resposta e parabéns pela palestra.

**Comment by otaviojava** [comment]
muito obrigado, no que precisar estamos ai
